export const SHOW_LOADER = "SHOW_LOADER";

export const ADD_USERINFO = "ADD_USERINFO";
export const FETCHED_USERINFO = "FETCHED_USERINFO";
export const CHANGE_USERINFO = "CHANGE_USERINFO";
export const REMOVE_USERINFOS = "REMOVE_USERINFOS";

export const ADD_DATES = "ADD_DATES";
export const CHANGE_DATES = "CHANGE_DATE";
export const FETCHED_DATES = "FETCHED_DATES";
export const REMOVE_DATES = "REMOVE_DATES";

export const ADD_CLIENT = "ADD_CLIENT";
export const CHANGE_CLIENT = "CHANGE_CLIENT";
export const FETCH_CLIENTS = "FETCH_CLIENTS";
export const REMOVE_CLIENT = "REMOVE_CLIENT";

export const ADD_PROJECT = "ADD_PROJECT";
export const CHANGE_PROJECT = "CHANGE_PROJECT";
export const CHANGE_PROJECTFORM = "CHANGE_PROJECTFORM";
export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const REMOVE_PROJECT = "REMOVE_PROJECT";

export const ADD_PAYMENT = "ADD_PAYMENT";
export const FETCH_PAYMENTS = "FETCH_PAYMENTS";
export const CHANGE_PAYMENT = "CHANGE_PAYMENT";
export const CHANGE_PAYMENTFORM = "CHANGE_PAYMENTFORM";
export const REMOVE_PAYMENT = "REMOVE_PAYMENT";



